### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by WuChenDi** [alex1504/femonitor-web#2]

**Comment by WuChenDi** [comment]
hi，你好，作者，想咨询下，在项目提供的地址打开demo演示页面，为什么开启了 rrweb 就会一直在输出内容的呢，如果这块数据上报到日志平台，如何关联吧用户行为关联起来的呢

**Comment by alex1504** [comment]
@WuChenDi 因为框架集成了rrweb，打开开关后会随着鼠标移动每次emit一个mouseTrack事件，demo页面rrweb队列参数限制为50。将这些数据上报到后台后基本就知道用户在页面上的鼠标轨迹了，但数据量比较大建议节流上报；和用户关联起来我理解是不是登录后用monitor.configData('uid', 'xxx')将uid设置到globalData中就ok了。

**Comment by WuChenDi** [comment]
你好，可能理解的不太对，我的想法是，如何利用rrweb的数据复现用户轨迹呢

**Comment by alex1504** [comment]
@WuChenDi  目前框架能做的是行为数据采集和上报，关于如何用rrweb回放轨迹可以搜索下一些相关文章。我找了两篇，希望对你有所帮助。
https://cloud.tencent.com/developer/article/1885763
https://juejin.cn/post/6918926609848205325

**Comment by WuChenDi** [comment]
done, ths

**Comment by WuChenDi** [comment]
不过大佬，你代码没有注释，有些地方的实现看的不太明白。。。

**Comment by alex1504** [comment]
@WuChenDi  有空我补充下注释

**Comment by WuChenDi** [comment]
@alex1504  ths, the confusion has been solved, issues is closed
