### ISSUE TITLE
fetch代理上报问题，并不是所有的返回数据都是json， 建议 reqEndRes.response 直接返回完整的 response，由用户自定义处理

### ISSUE THREAD

**Issue by iweijie** [alex1504/femonitor-web#3]
![image](https://user-images.githubusercontent.com/24514961/160745868-dae9b9ff-817e-4e28-be35-0e559db4ae49.png)

**Comment by alex1504** [comment]
1.4.3版本已优化，commit [3417338939f83f246ef1fb9ae44d2b6a97f3c78a](https://github.com/alex1504/femonitor-web/commit/3417338939f83f246ef1fb9ae44d2b6a97f3c78a)
